apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-qlec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-qlec
    app.kubernetes.io/part-of: test-app-ddqt
  name: test-component-qlec
  namespace: build-templates-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-qlec
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-qlec
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:aabc8ac490a64898a65df6ad53b89457
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
